### ISSUE TITLE
Closure reference bug

### ISSUE THREAD

**Issue by henrylee2cn** [wudaoluo/go-autoinstall#1]
https://github.com/wudaoluo/go-autoinstall/blob/03e089638a13dcc7434a490619a001f88afa81eb/cmd/autoinstall.go#L54

**Comment by wudaoluo** [comment]
servChan <- &s  将服务器信息发送 job 中,并发执行命令

**Comment by henrylee2cn** [comment]
I made a mistake
https://github.com/wudaoluo/go-autoinstall/blob/03e089638a13dcc7434a490619a001f88afa81eb/cmd/autoinstall.go#L53
